name: Parallel 20 Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-20-parallel:
    # Each matrix entry will spin up one runner, for a total of 20 parallel jobs
    runs-on: [kurgol-test-group]
    strategy:
      matrix:
        job-number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run job ${{ matrix.job-number }}
        run: |
          echo "Hello from job #${{ matrix.job-number }}!"
